name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push the Docker image
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ sercrets.PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nginx_gunicorn_docker_compose:$(date +%s)
    
