name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Push the Docker image
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag accenmagorgopella/nginx_kubsu:github
    - name: Push the Docker image
      run: docker push accenmagorgopella/nginx_kubsu:github
